events {
  worker_connections 1024;
}

http {
  include /etc/nginx/mime.types;
  default_type application/octet-stream;

  server {
    listen 80;

    location /api/ {
      proxy_pass http://apimonitor_backend:8080/api/;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
    }

    location /public/ {
      proxy_pass http://apimonitor_backend:8080/public/;
      proxy_set_header Host $host;
    }

    location / {
      proxy_pass http://apimonitor_frontend:80/;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
    }
  }
}
